export const CONSTANTS = {
  GET_MAIN_LIST: "GET_MAIN_LIST",

  ADD_CARD_FIREBASE: "ADD_CARD_FIREBASE",
  ADD_CARD_LOCALLY: "ADD_CARD_LOCALLY",

  REMOVE_CARD_FIREBASE: "REMOVE_CARD_FIREBASE",
  REMOVE_CARD_LOCALLY: "REMOVE_CARD_LOCALLY",

  ADD_LIST_FIREBASE: "ADD_LIST_FIREBASE",
  ADD_LIST_LOCALLY: "ADD_LIST_LOCALLY",

  UPDATE_CARD_LOCALLY: "UPDATE_CARD_LOCALLY",
  UPDATE_LIST_HEADING: "UPDATE_LIST_HEADING",

  REMOVE_LIST_FIREBASE: "REMOVE_LIST_FIREBASE",
  REMOVE_LIST_LOCALLY: "REMOVE_LIST_LOCALLY",

  HANDLE_DRAG_DROP: "HANDLE_DRAG_DROP",
};
