const data = {
  id: 0,
  title: "❤️ Demo",
  listCollection: [
    {
      cards: [
        {
          assignee: "choose 1: batman, ironman, hulk",
          date: 23,
          deadline: "enter deadline (month date)",
          description: "Add card description",
          heading: "Add card heading",
          hours: 22,
          id: "l3u0k7p",
          minutes: 51,
          month: "Mar",
          priority: "high",
          status: "Add status",
        },
        {
          assignee: "choose 1: batman, ironman, hulk",
          date: 23,
          deadline: "enter deadline (month date)",
          description: "Add card description",
          heading: "Add card heading",
          hours: 22,
          id: "l3u0wdk7p",
          minutes: 51,
          month: "Mar",
          priority: "low",
          status: "Add status",
        },
        {
          assignee: "choose 1: batman, ironman, hulk",
          date: 23,
          deadline: "enter deadline (month date)",
          description: "Add card description",
          heading: "Add card heading",
          hours: 22,
          id: "l3u0wdddk7p",
          minutes: 51,
          month: "Mar",
          priority: "moderate",
          status: "Add status",
        },
      ],
      heading: "Pending",
      id: "l13szot",
    },
    {
      cards: [
        {
          assignee: "choose 1: batman, ironman, hulk",
          date: 23,
          deadline: "enter deadline (month date)",
          description: "Add card description",
          heading: "Add card heading",
          hours: 22,
          id: "l3uk7p",
          minutes: 51,
          month: "Mar",
          priority: "low",
          status: "Add status",
        },
        {
          assignee: "choose 1: batman, ironman, hulk",
          date: 23,
          deadline: "enter deadline (month date)",
          description: "Add card description",
          heading: "Add card heading",
          hours: 22,
          id: "l3uk7ddp",
          minutes: 51,
          month: "Mar",
          priority: "high",
          status: "Add status",
        },
        {
          assignee: "choose 1: batman, ironman, hulk",
          date: 23,
          deadline: "enter deadline (month date)",
          description: "Add card description",
          heading: "Add card heading",
          hours: 22,
          id: "l3uk7asddp",
          minutes: 51,
          month: "Mar",
          priority: "high",
          status: "Add status",
        },
      ],
      heading: "in process",
      id: "l13szt",
    },

    {
      cards: [
        {
          assignee: "choose 1: batman, ironman, hulk",
          date: 23,
          deadline: "enter deadline (month date)",
          description: "Add card description",
          heading: "Add card heading",
          hours: 22,
          id: "l3up",
          minutes: 51,
          month: "Mar",
          priority: "high",
          status: "Add status",
        },
        {
          assignee: "choose 1: batman, ironman, hulk",
          date: 23,
          deadline: "enter deadline (month date)",
          description: "Add card description",
          heading: "Add card heading",
          hours: 22,
          id: "l3upwq",
          minutes: 51,
          month: "Mar",
          priority: "low",
          status: "Add status",
        },
      ],
      heading: "Done",
      id: "l1zt",
    },
  ],
};

export default data;
